reset;

model proj.mod;
data proj.dat;


option solver Gurobi;


solve;

param load_shed{n in ZONES};
let {n in ZONES} load_shed[n] := sum{t in TIME_PERIODS}  Curtailment[t,n];
	  

param total_demand;
let total_demand := sum{t in TIME_PERIODS,n in ZONES} fixed_demand[t,n];

display total_cost;
display total_cost/total_demand;
display capacity_installed_stor;
display capacity_installed_gen;
display load_shed;